# Creator: Eddy Elbrink
# Project: Inethi Network
# Service: Rocket.Chat
# Requirements: Rocket.Chat with MongoDB
#
# Rocket.Chat URL = "http://localhost:8082"
#

version: '3'

services:

  rocketchat:
    image: rocket.chat
    container_name: rocketchat-server
    ports:
      - 8082:3000
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      ROOT_URL: http://localhost
      MONGO_URL: mongodb://rocketchat-mongo:27017/meteor
    network_mode: "bridge"
    restart: on-failure

  mongo:
    image: mongo
    container_name: rocketchat-mongo
    volumes:
      - /mnt/data/rocketchat/mongo/data:/data/db
    command: --smallfiles
    network_mode: "bridge"
    restart: on-failure